import './globals.css'
import type { Metadata } from 'next'
import { Karla, Rubik } from 'next/font/google'

const karla = Karla({ subsets: ['latin'] })
const rubik = Rubik({ subsets: ['latin'], variable: '--font-rubik' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={rubik.variable}>
      <body className={karla.className}>{children}</body>
    </html>
  )
}
